// src/components/Nav.jsx
import React from 'react';
import styled from '@emotion/styled';

const Navbar = styled.nav`
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  background-color: #252525;
  box-shadow: 0 5px 15px #000;
  min-height: 7vh;
  font-weight: 600;
  font-size: 1.1rem;
`;
const NavList = styled.ul`
  list-style-type: none;
  display: flex;
  padding: 0.75rem;
  flex-direction: column;
  align-items: flex-end;

  @media screen and (min-width: 800px) {
    flex-direction: row;
    align-items: center;
    justify-content: flex-end;
  }
`;
const NavLink = styled.a`
  font-size: 1.3rem;
  margin-left: 1rem;
  text-decoration: none;
  color: #fafafa;
`;

const Nav = () => (
  <Navbar>
    <NavList>
      <li>
        <NavLink href="#">Games</NavLink>
      </li>
      <li>
        <NavLink href="#">Leagues</NavLink>
      </li>
      <li>
        <NavLink href="#">Login</NavLink>
      </li>
      <li>
        <NavLink href="#">Register</NavLink>
      </li>
    </NavList>
  </Navbar>
);

export default Nav;

// src/components/nav/Nav.vue
<template>
    <header class="nav">
        <router-link to="/" class="title">eSportacus</router-link>
        <MobileNavList :paths="paths" />
        <DesktopNavList :paths="paths" />
    </header>
</template>

<script lang='ts'>
import Vue from "vue";
import Component from "vue-class-component";
import MobileNavList from "./MobileNavList.vue";
import DesktopNavList from "./DesktopNavList.vue";

@Component({
    components: {
        MobileNavList,
        DesktopNavList,
    },
})
export default class Nav extends Vue {
    paths: Array<object> = [
        { id: `home`, path: `/` },
        { id: `games`, path: `/games` },
        { id: `leagues`, path: `/leagues` },
        { id: `login`, path: `/login` },
        { id: `register`, path: `/register` },
    ];
}
</script>

<style lang="scss" scoped>
.nav {
    background-color: $black;
    box-shadow: 0 5px 10px #111;
    height: 7vh;
    padding: 0 1rem;
    display: flex;
    justify-content: flex-end;
    align-items: center;

    @media screen and (min-width: 800px) {
        height: 10vh;
    }
    @media screen and (min-width: 1400px) {
        height: 7vh;
    }
}
.title {
    color: $white;
    font-size: 2.2rem;
    font-weight: 800;
    margin-right: auto;
    font-family: roboto;
    text-decoration: none;
}
</style>
